### ISSUE TITLE
Trying to download old version

### ISSUE THREAD

**Issue by Squash019** [tdsmith/homebrew-ham#2]
_chirp-daily-20170321_ is not found on the server since last version to date is **chirp-daily-20170401**, so the install fails. A fix would be handy.

Thank you!

**Comment by tdsmith** [comment]
Interesting; they don't normally remove old versions. Thanks for the nudge.

**Comment by tdsmith** [comment]
Oh, it's because I did a dumb thing in 947861e919f4e35bb8ea4931af232ef7115de613.

**Comment by tdsmith** [comment]
Fixed by 78e17e2.
