### ISSUE TITLE
brew install tdsmith/ham/chirp fails on High Sierra

### ISSUE THREAD

**Issue by beardeddog** [tdsmith/homebrew-ham#4]
macOS 10.13 (17A365)

$ brew install tdsmith/ham/chirp
==> Installing chirp from tdsmith/ham
==> Downloading http://trac.chirp.danplanet.com/chirp_daily/daily-20170714/chirp-daily-20170714.tar.gz
Already downloaded: /Users/weide/Library/Caches/Homebrew/chirp-20170714.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24c
Already downloaded: /Users/weide/Library/Caches/Homebrew/chirp--homebrew-virtualenv-15.1.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/chirp--homebrew-virtualenv-20171004-26515-krnw04/
Last 15 lines from /Users/weide/Library/Logs/Homebrew/chirp/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/chirp--homebrew-virtualenv-20171004-26515-krnw04/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tdsmith/homebrew-ham/issues

These open issues may also help:
brew install fails https://github.com/tdsmith/homebrew-ham/issues/3

$ brew doctor
Your system is ready to brew.

**Comment by tdsmith** [comment]
There's something weird about your Python environment. Can you share the output of `brew gist-logs chirp`?

**Comment by beardeddog** [comment]
yes, I would agree, I was able to install chirp on another macBook with no issues ... here is the output of brew gist-logs chirp

$ brew gist-logs chirp
https://gist.github.com/0aabc6d266de7b7f3776e7ed9b4b10a2

maybe I will just scrap off brew completely and start a fresh

**Comment by tdsmith** [comment]
`brew unlink python && brew link python` or `brew reinstall python` might be enough to kick it back into gear.

**Comment by beardeddog** [comment]
ok, that worked, thanks for the help
